language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

sudo: false

before_install:
  - travis_retry composer self-update

install:
  - composer install

script:
  - vendor/bin/phpunit -c phpunit.xml
  - vendor/bin/php-cs-fixer fix --dry-run --diff
